version: "3.6"

services:
  mosquitto: 
    image: eclipse-mosquitto:2.0.11
    ports: 
    - 1883:1883
    - 9001:9001
    volumes: 
    - mosquitto:/mosquitto/config
    - mosquitto:/mosquitto/data
    - mosquitto:/mosquitto/log
    privileged: true
    restart: unless-stopped
volumes: 
  mosquitto: 
   external: true
